<?php

/*
 * DO NOT EDIT THIS FILE MANUALLY.
 * If you want to contribute to translation, you must instead use the
 * SimpleSAMLphp translation portal:
 * https://translation.rnd.feide.no/index.php?aid=simplesamlphp
 *
 * This file is automatically generated from the translation portal.
 */

$lang = [
    'consent_accept' => [
        'en' => 'en:consent_accept',
        'es' => 'El servicio <b>SPNAME</b> requiere la siguiente información: ',
    ],
    'personal_info' => [
        'en' => 'en:personal_info',
        'es' => 'Conocer su identidad',
    ],
    'contact_info' => [
        'en' => 'en:contact_info',
        'es' => 'Conocer sus datos de contacto',
    ],
    'occupational_info' => [
        'en' => 'en:occupational_info',
        'es' => 'Conocer su vinculación laboral ',
    ],
    'identity_info' => [
        'en' => 'en:identity_info',
        'es' => 'Conocer sus identificadores ',
    ],
    'auth_info' => [
        'en' => 'en:auth_info',
        'es' => 'Conocer sus datos de autorización y/o derechos de acceso ',
    ],
    'others_info' => [
        'en' => 'en:others_info',
        'es' => 'Otra información ',
    ],
    'remember' => [
        'en' => 'en:remember',
        'es' => 'Recordar el consentimiento. ',
    ],
    'text_accept_withoutpolity' => [
        'en' => 'en:text_accept_withoutpolity',
        'es' => 'Al hacer clic en Permitir, autorizas a esta aplicación a usar la información según lo establecido en las condiciones de uso y la política de privacidad.',
    ],
    'text_accept' => [
        'en' => 'en:text_accept',
        'es' => 'Al hacer clic en Permitir, autorizas a esta aplicación a usar la información según lo establecido en las ',
    ],
    'text_accept_2' => [
        'en' => 'en:text_accept_2',
        'es' => 'condiciones de uso y la política de privacidad',
    ],
    'allow' => [
        'en' => 'en:allow',
        'es' => 'Permitir',
    ],
    'disallow' => [
        'en' => 'en:disallow',
        'es' => 'Denegar',
    ],
];
